### ISSUE TITLE
Add `DemoLink` component to the `mapbox.github.io/dr-ui/components/` library

### ISSUE THREAD

**Issue by domlet** [mapbox/dr-ui#402]
**Is your feature request related to a problem? Please describe.**

I wanted to send colleagues from our Imagery team to the https://mapbox.github.io/dr-ui/components/ library so they could see the `DemoLink` component, but it does not appear in this library.

**Describe the solution you'd like**

Can we add  the `DemoLink` component to https://mapbox.github.io/dr-ui/components/ library  ?

**Describe alternatives you've considered**

I could just share descriptive text [like this](https://github.com/mapbox/help/pull/2876#issuecomment-767627750).

**Additional context**

@katydecorah says:

> It will helpful to know if this component is needed for one or many repos
> if it's only used in /help then it should likely stay in help

**Comment by katydecorah** [comment]
@domlet since this component is only used in /help right now, how about adding documentation to https://github.com/mapbox/help/blob/publisher-production/docs/components.md?

Here's a great example for DemoIframe: https://github.com/mapbox/help/blob/publisher-production/docs/components.md#demo-iframe

**Comment by domlet** [comment]
Added to /help repo docs in https://github.com/mapbox/help/commit/1aff5f6b66cac7b50c351ceede7f5143f0f34568 – thanks @katydecorah!
