### ISSUE TITLE
Unstick sidebar content when going to a hash

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/dr-ui#61]
When going directly to a hash very far down on a page ([for example](https://www.mapbox.com/android-docs/maps/overview/styling-map/#style-related-events)) the sidebar content in the `PageLayout` component should not stick, but it does. 

![image](https://user-images.githubusercontent.com/10479155/48236805-b78f4280-e378-11e8-9670-cb4ba1b63acc.png)

@davidtheclark I'm wondering if it's a matter of the order in which things are happening because as soon as I scroll on the page the `Sticky` component snaps up to where it should be. Is there something I could do in componentDidMount if there is a hash in the URL? Or maybe it's more of an issue with the `Sticky` component we're using? Let me know if you have any thoughts that I could further 🕵️‍♀️ .

https://github.com/mapbox/dr-ui/blob/2e874553edb374e68988688c3c6c6ab6578459f4/src/components/page-layout/page-layout.js#L31-L34

cc @samfader

**Comment by davidtheclark** [comment]
Batfish's auto-scrolling (either to a hash or to a saved scroll location) happens here: https://github.com/mapbox/batfish/blob/503064de33ebffa407bbdf5d20e44a8c71964ccd/src/webpack/router.js#L70-L75 — in the Router's `componentDidMount`. 

I'm not sure right now whether the Router's `componentDidMount` will be called before or after its children's `componentDidMount`s (PageLayout will be a child of Router, I think). You could look into that. 

When Batfish autoscrolls, it uses `element.scrollIntoView()` (see https://github.com/mapbox/batfish/blob/503064de33ebffa407bbdf5d20e44a8c71964ccd/src/webpack/scroll-to-fragment.js). Chances are the Sticky component does not register that because it may not trigger a `scroll` event. You may want to set the PageLayout to automatically adjust the Sticky component's stickiness (if that's possible) after a short delay to allow fo the page to programmatically scroll first.
